name: linalg
description: A Simple Linear Algebra Package enabling easy Matrix calculations.
version: 0.4.0
homepage: https://github.com/altera2015/linalg


environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.17.9
  # coverage: ^1.0.3
  # grinder: ^0.9.0
  # grinder_coveralls: any
  